from .options import OPTIONS

SCHEMA_PORTCO = {
    "FI.ENV.12.00": {
        "label": "Production annuelle d'énergie renouvelable (MWh)",
        "type": "float",
        "min": 0,
    },
    "FI.GOV.02.00": {
        "label": "Nombre de femmes dans les organes non-exécutifs [PAI13 Tab1]",
        "type": "float",
        "min": 0,
    },
    "FI.GEN.07.00": {
        "label": "Nombre de salariés permanents en ETP à la fin de la période de reporting",
        "type": "float",
        "min": 0,
    },
    "FI.GEN.08.00": {
        "label": "Nombre de salariés non permanents en ETP à la fin de l'année de reporting",
        "type": "float",
        "min": 0,
    },
    "FI.GOV.01.00": {
        "label": "Nombre de membres dans les organes non-exécutifs [PAI13 Tab1]",
        "type": "float",
        "min": 0,
    },
    "FI.SOC.03.00": {
        "label": "Nombre de femmes dans les organes exécutifs",
        "type": "float",
        "min": 0,
    },
    "FI.SOC.04.01": {
        "label": "Index de l'égalité professionnelle entre les femmes et les hommes",
        "type": "float",
        "min": 0,
    },
    "FI.SOC.02.00": {
        "label": "Nombre de membres dans les organes exécutifs",
        "type": "float",
        "min": 0,
    },
    "FI.SOC.14.00": {
        "label": "Part d’employés actionnaires (%)",
        "type": "float",
        "min": 0,
        "max": 100,
    },
    "FI.SOC.15.00": {
        "label": "Part du capital détenu par les employés (%)",
        "type": "float",
        "min": 0,
        "max": 100,
    },
    "FI.GEN.09.00": {
        "label": "Nombre de salariés permanents en ETP à la fin de la période de reporting précédente (N-1)",
        "type": "float",
        "min": 0,
    },
    "FI.GEN.05.00": {
        "label": "Chiffre d'affaires consolidé net (M€)",
        "type": "float",
        "min": 0,
    },
    "FI.ENV.08.00": {
        "label": "Activités dans un secteur à fort impact climatique [PAI6 Tab1]",
        "type": "list",
        "schema": {"type": "string", "allowed": list(OPTIONS["fi_env_08_00"].keys())},
    },
    "FI.GOV.06.00": {
        "label": "Exposition à des armes controversées [PAI14, Tab1]",
        "type": "string",
        "allowed": ["YES", "NO"],
    },
    "FI.SOC.04.00": {
        "label": "Calcul de l'index d'égalité professionnelle",
        "type": "string",
        "allowed": list(OPTIONS["fi_soc_04_00"].keys()),
    },
    "FI.GOV.03.00": {
        "label": "Nombre de membres indépendants dans les organes non-exécutifs",
        "type": "float",
        "min": 0,
    },
    "FI.SOC.16.00": {
        "label": "Taux de fréquence d'accident du travail (%) [PAI2 Tab3]",
        "type": "float",
        "min": 0,
        "max": 100,
    },
    "FI.ENV.10.00": {
        "label": "Consommation annuelle d'énergie renouvelable (MWh)",
        "type": "float",
        "min": 0,
    },
    "FI.ENV.09.00": {
        "label": "Consommation totale d'énergie (MWh)",
        "type": "float",
        "min": 0,
    },
    "FI.ENV.11.00": {
        "label": "Production d'énergie totale (MWh)",
        "type": "float",
        "min": 0,
    },
    "FI.ENV.19.00": {
        "label": "Évaluation des dépendances en matière de biodiversité",
        "type": "string",
        "allowed": list(OPTIONS["fi_env_19_00"].keys()),
    },
    "FI.ENV.16.00": {
        "label": "Poids total des déchets radioactifs (t) [PAI9 Tab1]",
        "type": "float",
        "min": 0,
    },
    "FI.SOC.17.00": {
        "label": "Nombre de décès résultant d'accidents du travail et de maladies professionnelles",
        "type": "float",
        "min": 0,
    },
    "FI.SOC.18.00": {
        "label": "Nombre de jours de travail de salariés perdus pour accident ou maladie [PAI3 Tab3]",
        "type": "float",
        "min": 0,
    },
    "FI.ENV.17.00": {
        "label": "Sites situés dans ou à proximité des zones sensibles du point de vue de la biodiversité [PAI7 Tab1]",
        "type": "string",
        "allowed": ["YES", "NO"],
    },
    "FI.SOC.12.00": {
        "label": "Mécanisme de partage de la valeur",
        "type": "list",
        "schema": {"type": "string", "allowed": list(OPTIONS["fi_soc_12_00"].keys())},
    },
    "FI.GEN.03.00": {
        "label": "Classification des industries NACE",
        "type": "string",
        "allowed": list(OPTIONS["fi_gen_03_00"].keys()),
    },
    "FI.ENV.18.01": {
        "label": "Evaluations et mesures de réduction des risques et impacts en matière de  biodiversité [PAI7 Tab1]",
        "type": "string",
        "allowed": list(OPTIONS["fi_env_18_01"].keys()),
    },
    "FI.GEN.11.00": {
        "label": "Domaines couverts par votre politique de durabilité globale",
        "type": "list",
        "schema": {"type": "string", "allowed": list(OPTIONS["fi_gen_11_00"].keys())},
    },
    "FI.GEN.12.00": {
        "label": "Responsabilité et supervision en matière de durabilité",
        "type": "string",
        "allowed": ["YES", "NO"],
    },
    "FI.ENV.13.00": {
        "label": "Activités dans le secteur des combustibles fossiles [PAI4 Tab1]",
        "type": "string",
        "allowed": ["YES", "NO"],
    },
    "FI.SOC.09.00": {
        "label": "Mise en œuvre d'une enquête auprès des salariés",
        "type": "string",
        "allowed": list(OPTIONS["fi_soc_09_00"].keys()),
    },
    "FI.SOC.11.00": {
        "label": "Nombre moyen d'heures de formation (h/salarié)",
        "type": "float",
        "min": 0,
    },
    "FI.ENV.01.00": {
        "label": "Thématiques couvertes par la politique environnementale",
        "type": "list",
        "schema": {"type": "string", "allowed": list(OPTIONS["fi_env_01_00"].keys())},
    },
    "FI.GOV.04.00": {
        "label": "RSE abordée au sein des organes gouvernance au moins une fois par an",
        "type": "string",
        "allowed": ["YES", "NO"],
    },
    "FI.GOV.07.00": {
        "label": "Évaluation des questions de durabilité dans la chaîne d'approvisionnement",
        "type": "string",
        "allowed": list(OPTIONS["fi_gov_07_00"].keys()),
    },
    "FI.GOV.09.00": {
        "label": "Charte achats responsables",
        "type": "string",
        "allowed": list(OPTIONS["fi_gov_09_00"].keys()),
    },
    "FI.ENV.02.01": {
        "label": "Types d'émissions concernées par la cible de réduction des émissions de GES",
        "type": "list",
        "schema": {"type": "string", "allowed": list(OPTIONS["fi_env_02_01"].keys())},
    },
    "FI.GEN.04.00": {
        "label": "Code de l'unité monétaire de l'organisation (3 lettres)",
        "type": "string",
        "allowed": list(OPTIONS["fi_gen_04_00"].keys()),
    },
    "FI.ENV.04.00": {
        "label": "Volume des émissions de GES du Scope 1 (tCO2eq) [PAI1, 2, 3 Tab 1]*",
        "type": "float",
        "min": 0,
    },
    "FI.ENV.03.00": {
        "label": "Calcul des émissions de GES [PAI1,2,3 Tab1]",
        "type": "list",
        "schema": {"type": "string", "allowed": list(OPTIONS["fi_env_03_00"].keys())},
    },
    "FI.ENV.07.00": {
        "label": "Volume des émissions de GES du Scope 3 (tCO2eq) [PAI1, 2, 3 Tab1]*",
        "type": "float",
        "min": 0,
    },
    "FI.GEN.12.01": {
        "label": "Responsable de la stratégie, de la mise en ouvre et de la supervision des questions de durabilité",
        "type": "list",
        "schema": {"type": "string", "allowed": list(OPTIONS["fi_gen_12_01"].keys())},
    },
    "FI.GEN.01.00": {"label": "Nom de l'entreprise", "type": "string"},
    "FI.GEN.15.00": {
        "label": "Occurrence d'incidents RSE",
        "type": "list",
        "schema": {"type": "string", "allowed": list(OPTIONS["fi_gen_15_00"].keys())},
    },
    "FI.GEN.06.00": {
        "label": "Chiffre d'affaires au sein de l'UE (M€)",
        "type": "float",
        "min": 0,
    },
    "FI.GEN.10.00": {
        "label": "Nombre de salariés non permanents en ETP à la fin de l'année de reporting précédente (N-1)",
        "type": "float",
        "min": 0,
    },
    "FI.GEN.16.00": {
        "label": "Occurrence d'accidents RSE",
        "type": "string",
        "allowed": ["YES", "NO"],
    },
    "FI.ENV.02.03": {
        "label": "Méthode de calcul de la cible de réduction des émissions GES",
        "type": "string",
        "allowed": list(OPTIONS["fi_env_02_03"].keys()),
    },
    "FI.SOC.06.00": {
        "label": "Nombre d'embauches de salariés permanents en équivalent temps plein (ETP) durant la période de reporting, hors cession/acquisition",
        "type": "float",
        "min": 0,
    },
    "FI.SOC.07.00": {
        "label": "Nombre de départs de salariés permanents en équivalent temps plein (ETP) durant la période de reporting, hors cession/acquisition",
        "type": "float",
        "min": 0,
    },
    "FI.ENV.05.00": {
        "label": "Volume des émissions GES du scope 2 selon une méthode basée sur la localisation (tCO2eq) [PAI1, 2, 3, Tab1]*",
        "type": "float",
        "min": 0,
    },
    "FI.ENV.06.00": {
        "label": "Volume des émissions GES du scope 2 selon une méthode basée sur le marché (tCO2eq) [PAI1, 2, 3, Tab1]*",
        "type": "float",
        "min": 0,
    },
    "FI.SOC.08.00": {
        "label": "Taux d'absentéisme (%)*",
        "type": "float",
        "min": 0,
        "max": 100,
    },
    "FI.ENV.14.00": {
        "label": "Volume de substances prioritaires rejetées dans l'eau (t) [PAI8 Tab1]*",
        "type": "float",
        "min": 0,
    },
    "FI.SOC.05.00": {
        "label": "Écart de rémunération entre les femmes et les hommes (%) [PAI12 Tab1]*",
        "type": "float",
        "min": 0,
    },
    "FI.ENV.15.00": {
        "label": "Poids total des déchets dangereux (t) [PAI9 Tab1]*",
        "type": "float",
        "min": 0,
    },
    "FI.SOC.01.00": {
        "label": "Nombre de femmes salariées en équivalent temps plein (ETP)*",
        "type": "float",
        "min": 0,
    },
    "FI.GEN.13.00": {
        "label": "[FRANCE INVEST TEST] Procédures et mécanismes de contrôle du respect des principes internationaux [PAI11 Tab1]",
        "type": "string",
        "allowed": ["YES", "NO"],
    },
    "FI.GEN.14.00": {
        "label": "[FRANCE INVEST TEST] Violations des principes du PMNU ou des principes directeurs de l'OCDE à l'intention des entreprises multinationales [PAI10 Tab1]",
        "type": "string",
        "allowed": list(OPTIONS["fi_gen_14_00"].keys()),
    },
    "FI.GEN.17.00": {
        "label": "[FRANCE INVEST TEST] Évaluation de la part d'activités éligibles et alignées à la taxonomie de l'UE",
        "type": "string",
        "allowed": list(OPTIONS["fi_gen_17_00"].keys()),
    },
    "FI.ENV.02.00": {
        "label": "[FRANCE INVEST TEST] Cible en matière de réduction des émissions de GES [PAI4 Tab2]",
        "type": "string",
        "allowed": ["YES", "NO"],
    },
    "FI.SOC.10.00": {
        "label": "[FRANCE INVEST TEST] Procédure de lancement d'alertes et de gestion des plaintes [PAI5 Tab3]",
        "type": "string",
        "allowed": list(OPTIONS["fi_soc_10_00"].keys()),
    },
    "FI.GOV.08.00": {
        "label": "[FRANCE INVEST TEST] Sujets intégrés dans le processus d'évaluation des questions de durabilité dans la chaîne d'approvisionnement",
        "type": "list",
        "schema": {"type": "string", "allowed": list(OPTIONS["fi_gov_08_00"].keys())},
    },
    "FI.ENV.03.01": {
        "label": "[FRANCE INVEST TEST] Méthodologie suivie pour le bilan carbone",
        "type": "string",
        "allowed": list(OPTIONS["fi_env_03_01"].keys()),
    },
    "FI.ENV.02.02": {
        "label": "[FRANCE INVEST TEST] Horizon de l'objectif de réduction des émissions de GES",
        "type": "string",
        "allowed": list(OPTIONS["fi_env_02_02"].keys()),
    },
    "FI.GEN.02.00": {
        "label": "[FRANCE INVEST TEST] Pays d'établissement",
        "type": "string",
        "allowed": list(OPTIONS["fi_gen_02_00"].keys()),
    },
    "FI.SOC.13.00": {
        "label": "[FRANCE INVEST TEST] Méthode d'attribution d'actions gratuites",
        "type": "string",
        "allowed": list(OPTIONS["fi_soc_13_00"].keys()),
    },
    "FI.ENV.18.00": {
        "label": "[FRANCE INVEST TEST] Activités ayant une incidence négative sur des zones clés de biodiversité [PAI7 Tab1]",
        "type": "string",
        "allowed": list(OPTIONS["fi_env_18_00"].keys()),
    },
    "FI.GOV.05.00": {
        "label": "[FRANCE INVEST TEST] Code de déontologie / Code éthique",
        "type": "string",
        "allowed": ["YES", "NO"],
    },
}

COMPOUND_ID_UNITS = {
    "FI.ENV.12.00": "MWh",
    "FI.GOV.02.00": "femme(s)",
    "FI.GEN.07.00": "ETP",
    "FI.GEN.08.00": "ETP",
    "FI.GOV.01.00": "membre(s)",
    "FI.SOC.03.00": "effectif(s)",
    "FI.SOC.04.01": "/100",
    "FI.SOC.02.00": "membre(s)",
    "FI.GEN.09.00": "ETP",
    "FI.GEN.05.00": "M€",
    "FI.GOV.03.00": "indépendant(s)",
    "FI.ENV.10.00": "MWh",
    "FI.ENV.09.00": "MWh",
    "FI.ENV.11.00": "mWh",
    "FI.ENV.16.00": "tonne(s)",
    "FI.SOC.17.00": "décès",
    "FI.SOC.18.00": "jours",
    "FI.SOC.11.00": "h / salarié",
    "FI.ENV.04.00": "tCO2éq",
    "FI.ENV.07.00": "tCO2eq",
    "FI.GEN.06.00": "M€",
    "FI.GEN.10.00": "ETP",
    "FI.SOC.06.00": "Embauche(s)",
    "FI.SOC.07.00": "Départ(s)",
    "FI.ENV.05.00": "tCO2éq",
    "FI.ENV.06.00": "tCO2éq",
    "FI.ENV.14.00": "tonne(s)",
    "FI.SOC.05.00": "%",
    "FI.ENV.15.00": "tonne(s)",
    "FI.SOC.01.00": "ETP",
}
