from .options import OPTIONS

SCHEMA_PORTCO = {
    "FI.GEN.01.00": {"label": "Company name", "type": "string"},
    "FI.GEN.18.00": {"label": "Company's website", "type": "string"},
    "FI.GEN.19.00": {"label": "Company's ID", "type": "float", "min": 0},
    "FI.GEN.02.00": {
        "label": "Country of establishment",
        "type": "string",
        "allowed": list(OPTIONS["fi_gen_02_00"].keys()),
    },
    "FI.GEN.03.00": {
        "label": "Industry classification",
        "type": "string",
        "allowed": list(OPTIONS["fi_gen_03_00"].keys()),
    },
    "FI.GEN.04.00": {
        "label": "Currency",
        "type": "string",
        "allowed": list(OPTIONS["fi_gen_04_00"].keys()),
    },
    "FI.GEN.05.00": {"label": "Revenue", "type": "float", "min": 0},
    "FI.GEN.20.00": {
        "label": "Exposure to controversial sectors",
        "type": "list",
        "schema": {"type": "string", "allowed": list(OPTIONS["fi_gen_20_00"].keys())},
    },
    "FI.GEN.07.00": {
        "label": "Number of permanent FTE employees at end of reporting year",
        "type": "float",
        "min": 0,
    },
    "FI.GEN.08.00": {
        "label": "Number of non permanent FTE employees at end of reporting year",
        "type": "float",
        "min": 0,
    },
    "FI.GEN.09.00": {
        "label": "Number of permanent FTE employees at end of previous reporting year (N-1)",
        "type": "float",
        "min": 0,
    },
    "FI.GEN.10.00": {
        "label": "Number of non permanent FTE employees at end of previous reporting year (N-1)",
        "type": "float",
        "min": 0,
    },
    "FI.GEN.11.00": {
        "label": "Formalized sustainability-related policies",
        "type": "list",
        "schema": {"type": "string", "allowed": list(OPTIONS["fi_gen_11_00"].keys())},
    },
    "FI.GEN.12.01": {
        "label": "Responsible for the company's sustainability matters",
        "type": "list",
        "schema": {"type": "string", "allowed": list(OPTIONS["fi_gen_12_01"].keys())},
    },
    "FI.GEN.13.00": {
        "label": "Policies to monitor compliance with the UNGC principles or OECD Guidelines",
        "type": "string",
        "allowed": ["YES", "NO"],
    },
    "FI.GEN.14.00": {
        "label": "Involvement in violations of the UNGC principles or OECD Guidelines for Multinational Enterprises",
        "type": "string",
        "allowed": list(OPTIONS["fi_gen_14_00"].keys()),
    },
    "FI.GEN.15.00": {
        "label": "Occurrence of CSR incidents",
        "type": "list",
        "schema": {"type": "string", "allowed": list(OPTIONS["fi_gen_15_00"].keys())},
    },
    "FI.GEN.17.00": {
        "label": "Assessment of the proportion of activities eligible and aligned to the EU Taxonomy",
        "type": "string",
        "allowed": list(OPTIONS["fi_gen_17_00"].keys()),
    },
    "FI.GEN.17.01": {
        "label": "EU Taxonomy alignment - % turnover",
        "type": "float",
        "min": 0,
        "max": 100,
    },
    "FI.GEN.17.02": {
        "label": "EU Taxonomy alignment - % CapEx",
        "type": "float",
        "min": 0,
        "max": 100,
    },
    "FI.ENV.20.00": {
        "label": "Climate risks assessment",
        "type": "list",
        "schema": {"type": "string", "allowed": list(OPTIONS["fi_env_20_00"].keys())},
    },
    "FI.ENV.21.00": {
        "label": "GHG emissions reduction plan or strategy",
        "type": "string",
        "allowed": list(OPTIONS["fi_env_21_00"].keys()),
    },
    "FI.ENV.21.01": {
        "label": "Short term GHG reduction target ",
        "type": "string",
        "allowed": list(OPTIONS["fi_env_21_01"].keys()),
    },
    "FI.ENV.21.02": {
        "label": "Short term GHG reduction target  - scope",
        "type": "list",
        "schema": {"type": "string", "allowed": list(OPTIONS["fi_env_21_02"].keys())},
    },
    "FI.ENV.21.03": {
        "label": 'Long term "Net zero emissions" target',
        "type": "string",
        "allowed": list(OPTIONS["fi_env_21_03"].keys()),
    },
    "FI.ENV.21.04": {
        "label": "Respect of the GHG emissions reduction target set",
        "type": "string",
        "allowed": list(OPTIONS["fi_env_21_04"].keys()),
    },
    "FI.ENV.01.00": {
        "label": "Other environmental action plans",
        "type": "list",
        "schema": {"type": "string", "allowed": list(OPTIONS["fi_env_01_00"].keys())},
    },
    "FI.ENV.03.00": {
        "label": "Calculation of GHG emissions",
        "type": "list",
        "schema": {"type": "string", "allowed": list(OPTIONS["fi_env_03_00"].keys())},
    },
    "FI.ENV.04.00": {"label": "Scope 1 GHG emissions", "type": "float", "min": 0},
    "FI.ENV.05.00": {"label": "Scope 2 GHG emissions", "type": "float", "min": 0},
    "FI.ENV.07.00": {"label": "Scope 3 GHG emissions", "type": "float", "min": 0},
    "FI.ENV.08.00": {
        "label": "Active in high impact climate sector",
        "type": "string",
        "allowed": list(OPTIONS["fi_env_08_00"].keys()),
    },
    "FI.ENV.09.00": {"label": "Total energy consumption", "type": "float", "min": 0},
    "FI.ENV.10.00": {
        "label": "Renewable energy consumption",
        "type": "float",
        "min": 0,
    },
    "FI.ENV.22.00": {
        "label": "Energy production",
        "type": "string",
        "allowed": ["YES", "NO"],
    },
    "FI.ENV.22.01": {
        "label": "Energy production - GHG intensity above 100gCO2e/kWh",
        "type": "string",
        "allowed": ["YES", "NO"],
    },
    "FI.ENV.11.00": {"label": "Total energy production", "type": "float", "min": 0},
    "FI.ENV.12.00": {"label": "Renewable energy production", "type": "float", "min": 0},
    "FI.ENV.13.00": {
        "label": "Activities in the fossil fuel sector",
        "type": "string",
        "allowed": ["YES", "NO"],
    },
    "FI.ENV.14.00": {"label": "Emissions to water", "type": "float", "min": 0},
    "FI.ENV.23.00": {
        "label": "Hazardous and radioactive waste generated (tonnes)",
        "type": "float",
        "min": 0,
    },
    "FI.ENV.17.00": {
        "label": "Activities located in or near biodiversity-sensitive areas",
        "type": "string",
        "allowed": list(OPTIONS["fi_env_17_00"].keys()),
    },
    "FI.ENV.18.00": {
        "label": "Activities negatively affecting biodiversity-sensitive areas",
        "type": "string",
        "allowed": list(OPTIONS["fi_env_18_00"].keys()),
    },
    "FI.ENV.18.01": {
        "label": "Biodiversity-sensitive areas assessment",
        "type": "string",
        "allowed": list(OPTIONS["fi_env_18_01"].keys()),
    },
    "FI.ENV.19.00": {
        "label": "Impacts and dependencies on biodiversity assessment",
        "type": "string",
        "allowed": list(OPTIONS["fi_env_19_00"].keys()),
    },
    "FI.SOC.01.00": {
        "label": "Female Full Time Equivalent workers (FTEs)",
        "type": "float",
        "min": 0,
    },
    "FI.SOC.02.00": {
        "label": "Number of members of the executive committee",
        "type": "float",
        "min": 0,
    },
    "FI.SOC.03.00": {
        "label": "Number of women on the executive committee",
        "type": "float",
        "min": 0,
    },
    "FI.SOC.04.01": {"label": "Gender equality Index score", "type": "float", "min": 0},
    "FI.SOC.05.00": {
        "label": "Unadjusted gender pay gap",
        "type": "float",
        "min": -100,
        "max": 100,
    },
    "FI.SOC.06.00": {
        "label": "Number of permanent Full Time Equivalents (FTEs) hires during the current reporting year, excluding divestitures/acquisitions",
        "type": "float",
        "min": 0,
    },
    "FI.SOC.07.00": {
        "label": "Number of permanent Full Time Equivalents (FTEs) departures during the current reporting year, excluding divestitures/acquisitions",
        "type": "float",
        "min": 0,
    },
    "FI.SOC.08.00": {
        "label": "Absenteeism rate",
        "type": "float",
        "min": 0,
        "max": 100,
    },
    "FI.SOC.09.00": {
        "label": "Implementation of an employee survey",
        "type": "string",
        "allowed": list(OPTIONS["fi_soc_09_00"].keys()),
    },
    "FI.SOC.11.00": {"label": "Training and education", "type": "float", "min": 0},
    "FI.SOC.12.00": {
        "label": "Profit-sharing system",
        "type": "list",
        "schema": {"type": "string", "allowed": list(OPTIONS["fi_soc_12_00"].keys())},
    },
    "FI.SOC.14.00": {
        "label": "Share of employee shareholders among all permanent employees",
        "type": "float",
        "min": 0,
        "max": 100,
    },
    "FI.SOC.15.00": {
        "label": "Share of capital detained by employees",
        "type": "float",
        "min": 0,
        "max": 100,
    },
    "FI.SOC.16.00": {
        "label": "Work-related injury frequency rate",
        "type": "float",
        "min": 0,
    },
    "FI.SOC.17.00": {
        "label": "Number of work-related fatalities",
        "type": "float",
        "min": 0,
    },
    "FI.SOC.18.00": {
        "label": "Number of days lost to injuries, accidents, fatalities or illness",
        "type": "float",
        "min": 0,
    },
    "FI.GOV.01.00": {
        "label": "Total number of board members",
        "type": "float",
        "min": 0,
    },
    "FI.GOV.02.00": {
        "label": "Number of women board members",
        "type": "float",
        "min": 0,
    },
    "FI.GOV.03.00": {
        "label": "Number of independent board members",
        "type": "float",
        "min": 0,
    },
    "FI.GOV.04.00": {
        "label": "Sustainability at the Board",
        "type": "string",
        "allowed": ["YES", "NO"],
    },
    "FI.GOV.10.00": {
        "label": "Business Ethics policies",
        "type": "list",
        "schema": {"type": "string", "allowed": list(OPTIONS["fi_gov_10_00"].keys())},
    },
    "FI.GOV.06.00": {
        "label": "Exposure to controversial weapons",
        "type": "string",
        "allowed": ["YES", "NO"],
    },
    "FI.GOV.11.00": {
        "label": "Responsible procurement charter and/or charter",
        "type": "list",
        "schema": {"type": "string", "allowed": list(OPTIONS["fi_gov_11_00"].keys())},
    },
    "FI.GOV.07.00": {
        "label": "Supply chain screening for Sustainability-related issues",
        "type": "string",
        "allowed": list(OPTIONS["fi_gov_07_00"].keys()),
    },
    "FI.GOV.08.00": {
        "label": "If yes, which of the the following components includes your company's supply chain screening process for CSR-related issues",
        "type": "list",
        "schema": {"type": "string", "allowed": list(OPTIONS["fi_gov_08_00"].keys())},
    },
}

COMPOUND_ID_UNITS = {
    "FI.GEN.05.00": "M€",
    "FI.GEN.17.01": "%",
    "FI.GEN.17.02": "%",
    "FI.ENV.04.00": "tCO2e",
    "FI.ENV.05.00": "tCO2e",
    "FI.ENV.07.00": "tCO2e",
    "FI.ENV.09.00": "MWh",
    "FI.ENV.10.00": "MWh",
    "FI.ENV.11.00": "MWh",
    "FI.ENV.12.00": "MWh",
    "FI.ENV.14.00": "tonnes",
    "FI.ENV.23.00": "tonnes",
    "FI.SOC.05.00": "%",
    "FI.SOC.08.00": "%",
    "FI.SOC.11.00": "h/employee",
    "FI.SOC.14.00": "%",
    "FI.SOC.15.00": "%",
    "FI.SOC.18.00": "days",
}
